#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Three Desi Things
title: Three Desi Things
subtitle: Unknown stories about the food, culture, and people of India and South Asia.

# Name of the author
author: Three Desi Beings

summary: Three desis — one Indian and two Indian-Americans — banter and joke with each other while discovering little-known facts about the food, culture, and people of India and South Asia.

# Short bio or description (displayed in the header)
description: Unknown stories about the food, culture, and people of India and South Asia..

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/tdt-logo.jpg
og: /images/tdt-logo.jpg

# Do not generate posts/episodes in the future
future: false

#
# Podcast settings
#

keywords:       "food, culture, travel, india, south asia, history"

explicit:       "no"
type:           "episodic" # 'serial' or 'episodic'

lang:           "en"
launch_date:	  2020-12-25
copyright:      "&#x2117; &amp; &#xA9; 2020"
email: threedesithings@gmail.com

podcast-feed:			"https://nullpointers.io/feed/podcast.rss"
apple-podcasts-feed:	"https://podcasts.apple.com/podcast/null-pointers/id1512641994"
spotify-podcasts-feed:	"https://open.spotify.com/show/6X2km5VppEVYIdVjExWlgt?si=x3be9oJZRYKjfDxp_tTPhQ"
overcast-podcasts-feed:	"https://overcast.fm/itunes1512641994/null-pointers"
pocketcasts-podcasts-feed: "https://pca.st/podcast/7f97b040-74ca-0138-eddb-0acc26574db2"
google-podcasts-feed: "https://podcasts.google.com/?feed=aHR0cHM6Ly9udWxscG9pbnRlcnMuaW8vZmVlZC9wb2RjYXN0LnJzcw"
stitcher-podcasts-feed: "https://www.stitcher.com/podcast/null-pointers"

# Site Settings
image-path: /images/

# Artwork
podcast-artwork: "tdt-logo.jpg"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: threedesithings@gmail.com
  facebook:
  flickr:
  instagram:
  linkedin: 
  pinterest:
  twitter: threedesithings
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-451KCTTCE1

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: https://threedesithings.com
enforce_ssl: https://threedesithings.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

